services:
  vortexdns:
    build: .
    image: vortexdns:latest
    container_name: vortexdns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "8080:8080/tcp"
    volumes:
      - ./config.json:/app/config.json
      - vortex_data:/app/vortex_db
      - vortex_logs:/app/logs
    restart: unless-stopped

volumes:
  vortex_data:
  vortex_logs:
